### ISSUE TITLE
PIP error : No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by rsaikali** [rsaikali/django-skwissh#3]
Error while trying to install via `pip` :

```
$ pip install django-skwissh
Downloading/unpacking django-skwissh
  Downloading django-skwissh-0.0.3.zip (270Kb): 270Kb downloaded
  Running setup.py egg_info for package django-skwissh
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/rsaikali/testpip/testenv/build/django-skwissh/setup.py", line 25, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), 'README.rst')).read(),
    IOError: [Errno 2] No such file or directory: '/home/rsaikali/testpip/testenv/build/django-skwissh/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/rsaikali/testpip/testenv/build/django-skwissh/setup.py", line 25, in <module>

  long_description=open(os.path.join(os.path.dirname(__file__), 'README.rst')).read(),

IOError: [Errno 2] No such file or directory: '/home/rsaikali/testpip/testenv/build/django-skwissh/README.rst'

Command python setup.py egg_info failed with error code 1 in /home/rsaikali/testpip/testenv/build/django-skwissh
Storing complete log in /home/rsaikali/.pip/pip.log
```

**Comment by rsaikali** [comment]
Corrected in v0.0.4
